name: Trigger auto deployment for camp-web

on:
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/camp-web-AutoDeployTrigger-ef025bff-8141-49b2-bc96-f8e5f70cad14.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write 
      contents: read 

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAMPWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAMPWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAMPWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          # ğŸ›‘ Ø§Ù„ØªØ¹Ø¯ÙŠÙ„ 1: Ù†Ø¬Ø¹Ù„ Ù…Ø³Ø§Ø± Ø§Ù„Ù…ØµØ¯Ø± Ù‡Ùˆ Ø¬Ø°Ø± Ø§Ù„Ù…Ø´Ø±ÙˆØ¹ Ø¨Ø§Ù„ÙƒØ§Ù…Ù„
          appSourcePath: ${{ github.workspace }}
          
          # ğŸ›‘ Ø§Ù„ØªØ¹Ø¯ÙŠÙ„ 2: Ù†Ø­Ø¯Ø¯ Ù…ÙƒØ§Ù† Ù…Ù„Ù Ø§Ù„Ø¯ÙˆÙƒØ± Ø¨Ø¯Ù‚Ø© Ø¨Ø§Ù„Ù†Ø³Ø¨Ø© Ù„Ù„Ø¬Ø°Ø±
          dockerfilePath: docker/local/django/Dockerfile

          registryUrl: campregistry2026.azurecr.io
          registryUsername: ${{ secrets.CAMPWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAMPWEB_REGISTRY_PASSWORD }}
          containerAppName: camp-web
          resourceGroup: MedCamp-RG
          imageToBuild: campregistry2026.azurecr.io/camp-web:${{ github.sha }}
